const SUPABASE_URL=(import.meta.env.VITE_SUPABASE_URL||'').trim().replace(/\/+$/,'');
const SUPABASE_ANON_KEY=(import.meta.env.VITE_SUPABASE_ANON_KEY||'').trim();
const SESSION_KEY='nesevren-auth-session-v1';
const PROFILE_KEY='nesevren-user-profile-v1';
const configured=Boolean(SUPABASE_URL&&SUPABASE_ANON_KEY);
let currentUser=null;
let menuEl=null;

function readJson(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
function writeJson(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function removeKey(key){try{localStorage.removeItem(key)}catch{}}
function closeBackdrop(){document.querySelector('.authBackdrop')?.remove()}
function closeMenu(){menuEl?.remove();menuEl=null}
function initials(name=''){const p=name.trim().split(/\s+/).filter(Boolean);return (p[0]?.[0]||'K')+(p[1]?.[0]||'')}
function profile(){return readJson(PROFILE_KEY)||null}
function session(){return readJson(SESSION_KEY)||null}
function displayName(){const p=profile();return p?.name||currentUser?.user_metadata?.full_name||currentUser?.user_metadata?.name||currentUser?.email||currentUser?.phone||'Profil'}
function authHeaders(token=SUPABASE_ANON_KEY){return{'Content-Type':'application/json','apikey':SUPABASE_ANON_KEY,'Authorization':`Bearer ${token}`}}
function setupMessage(){return configured?'':'Google, Apple ve SMS girişlerinin çalışması için Render ortamına VITE_SUPABASE_URL ve VITE_SUPABASE_ANON_KEY eklenmeli; Supabase panelinde Google, Apple ve Phone sağlayıcıları etkinleştirilmeli.'}

async function fetchUser(accessToken){if(!configured||!accessToken)return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:authHeaders(accessToken)});if(!r.ok)return null;return await r.json()}
async function restore(){const hash=new URLSearchParams(location.hash.replace(/^#/,''));const access=hash.get('access_token');if(access){const s={access_token:access,refresh_token:hash.get('refresh_token')||'',expires_at:Date.now()+Number(hash.get('expires_in')||3600)*1000};writeJson(SESSION_KEY,s);history.replaceState(null,'',location.pathname+location.search)}const s=session();if(s?.access_token)currentUser=await fetchUser(s.access_token);enhanceHeader();if(currentUser&&!profile())setTimeout(openProfileSetup,120)}
function enhanceHeader(){const status=document.querySelector('.appTopbar .aiStatus');if(!status)return;if(status.dataset.authReady==='1')return;status.dataset.authReady='1';status.className='authEntry';status.innerHTML='';status.type='button';status.addEventListener('click',e=>{e.preventDefault();closeMenu();if(currentUser)openAccountMenu(status);else openLogin()});renderEntry(status)}
function renderEntry(button=document.querySelector('.appTopbar .authEntry')){if(!button)return;if(currentUser){const name=displayName();button.innerHTML=`<span class="authAvatar">${initials(name).toUpperCase()}</span><span>${escapeHtml(name.length>18?name.slice(0,16)+'…':name)}</span>`}else button.innerHTML='<span class="authAvatar">👤</span><span>Giriş Yap</span>'}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function modalShell(title,description,content){closeBackdrop();const wrap=document.createElement('div');wrap.className='authBackdrop';wrap.innerHTML=`<section class="authModal"><button class="authClose" aria-label="Kapat">×</button><div class="authHead"><h2>${title}</h2><p>${description}</p></div>${content}</section>`;document.body.appendChild(wrap);wrap.querySelector('.authClose').onclick=closeBackdrop;wrap.addEventListener('click',e=>{if(e.target===wrap)closeBackdrop()});return wrap}
function openLogin(){const note=setupMessage();const wrap=modalShell('Neşevren’e giriş yap','Hesabınla giriş yaptığında öğrenme geçmişin ve kişisel profilin aynı kullanıcıyla eşleştirilebilir.',`<div class="authProviders"><button class="authProvider" data-provider="google"><span>G</span>Google ile devam et</button><button class="authProvider" data-provider="apple"><span></span>Apple ile devam et</button></div><div class="authDivider">veya</div><div class="authPhone"><div class="authField"><label>Cep telefonu</label><input id="authPhone" type="tel" inputmode="tel" placeholder="+90 5xx xxx xx xx" autocomplete="tel"></div><button class="authPrimary" id="sendOtp">Telefonla devam et</button></div><div id="authMsg"></div>${note?`<div class="authSetupNote">${note}</div>`:''}`);wrap.querySelectorAll('[data-provider]').forEach(btn=>btn.addEventListener('click',()=>startOAuth(btn.dataset.provider,wrap)));wrap.querySelector('#sendOtp').onclick=()=>sendOtp(wrap)}
function startOAuth(provider,wrap){if(!configured){setMsg(wrap,'Kimlik doğrulama servisi henüz yapılandırılmadı. Önce Supabase bağlantı bilgileri eklenmeli.',true);return}const redirect=location.origin+location.pathname;location.assign(`${SUPABASE_URL}/auth/v1/authorize?provider=${encodeURIComponent(provider)}&redirect_to=${encodeURIComponent(redirect)}`)}
function normalizePhone(v){let s=v.replace(/[^+\d]/g,'');if(s.startsWith('0'))s='+90'+s.slice(1);if(/^5\d{9}$/.test(s))s='+90'+s;return s}
async function sendOtp(wrap){if(!configured){setMsg(wrap,'Telefonla giriş için Supabase bağlantısı henüz yapılandırılmadı.',true);return}const input=wrap.querySelector('#authPhone');const phone=normalizePhone(input.value.trim());if(!/^\+\d{10,15}$/.test(phone)){setMsg(wrap,'Telefon numarasını ülke koduyla yazın. Örnek: +90 5xx xxx xx xx',true);return}setMsg(wrap,'Doğrulama kodu gönderiliyor…');try{const r=await fetch(`${SUPABASE_URL}/auth/v1/otp`,{method:'POST',headers:authHeaders(),body:JSON.stringify({phone,create_user:true})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.msg||data?.message||'Kod gönderilemedi.');showOtpVerify(wrap,phone)}catch(e){setMsg(wrap,e.message||'Kod gönderilemedi.',true)}}
function showOtpVerify(wrap,phone){const phoneBox=wrap.querySelector('.authPhone');phoneBox.innerHTML=`<div class="authField"><label>${escapeHtml(phone)} numarasına gelen kod</label><input id="authOtp" type="text" inputmode="numeric" maxlength="8" placeholder="Doğrulama kodu" autocomplete="one-time-code"></div><button class="authPrimary" id="verifyOtp">Kodu doğrula</button><button class="authSecondary" id="changePhone">Numarayı değiştir</button>`;phoneBox.querySelector('#verifyOtp').onclick=()=>verifyOtp(wrap,phone);phoneBox.querySelector('#changePhone').onclick=openLogin;setMsg(wrap,'SMS doğrulama kodunu girin.')}
async function verifyOtp(wrap,phone){const token=wrap.querySelector('#authOtp')?.value.trim();if(!token){setMsg(wrap,'Doğrulama kodunu yazın.',true);return}setMsg(wrap,'Kod doğrulanıyor…');try{const r=await fetch(`${SUPABASE_URL}/auth/v1/verify`,{method:'POST',headers:authHeaders(),body:JSON.stringify({type:'sms',phone,token})});const data=await r.json().catch(()=>({}));if(!r.ok||!data.access_token)throw new Error(data?.msg||data?.message||'Kod doğrulanamadı.');writeJson(SESSION_KEY,{access_token:data.access_token,refresh_token:data.refresh_token||'',expires_at:Date.now()+(data.expires_in||3600)*1000});currentUser=data.user||await fetchUser(data.access_token);closeBackdrop();renderEntry();if(!profile())openProfileSetup()}catch(e){setMsg(wrap,e.message||'Kod doğrulanamadı.',true)}}
function setMsg(wrap,text,isError=false){const el=wrap.querySelector('#authMsg');if(!el)return;el.className=`authMessage${isError?' error':''}`;el.textContent=text}

const roles=[['student','🎓 Öğrenci'],['teacher','👩‍🏫 Öğretmen / Eğitmen'],['parent','👨‍👩‍👧 Veli'],['professional','💼 Profesyonel / Çalışan'],['business','🏢 İşletme sahibi / Girişimci'],['other','◌ Diğer']];
function detailFields(role,p={}){if(role==='student')return `<div class="authField"><label>Sınıf / seviye</label><input name="detail" value="${escapeHtml(p.detail||'')}" placeholder="Örn. 8. sınıf, TYT, üniversite"></div><div class="authField"><label>İlgilendiğin dersler</label><input name="secondary" value="${escapeHtml(p.secondary||'')}" placeholder="Örn. Matematik, Fizik, İngilizce"></div>`;if(role==='teacher')return `<div class="authField"><label>Branş / uzmanlık</label><input name="detail" value="${escapeHtml(p.detail||'')}" placeholder="Örn. Matematik öğretmeni"></div><div class="authField"><label>Çalıştığın seviye</label><input name="secondary" value="${escapeHtml(p.secondary||'')}" placeholder="Örn. Ortaokul, lise, YKS"></div>`;if(role==='parent')return `<div class="authField"><label>Öğrencinin sınıfı / seviyesi</label><input name="detail" value="${escapeHtml(p.detail||'')}" placeholder="Örn. 6. sınıf"></div>`;if(role==='business')return `<div class="authField"><label>Sektör / iş alanı</label><input name="detail" value="${escapeHtml(p.detail||'')}" placeholder="Örn. eğitim, perakende, inşaat"></div>`;if(role==='professional')return `<div class="authField"><label>Meslek / uzmanlık alanı</label><input name="detail" value="${escapeHtml(p.detail||'')}" placeholder="Örn. mühendis, muhasebeci, yazılımcı"></div>`;return `<div class="authField"><label>Kullanım amacın</label><input name="detail" value="${escapeHtml(p.detail||'')}" placeholder="Kısaca yazabilirsin"></div>`}
function openProfileSetup(){const p=profile()||{};let selected=p.role||'student';const suggested=currentUser?.user_metadata?.full_name||currentUser?.user_metadata?.name||'';const wrap=modalShell('Profilini tamamla','Neşevren içeriği ve önerileri sana daha uygun hale getirmek için birkaç kısa bilgi ister.',`<form class="authProfileForm" id="profileForm"><div class="authField"><label>Ad / görünen ad</label><input name="name" value="${escapeHtml(p.name||suggested)}" placeholder="Adın"></div><div><div class="authField"><label>Neşevren’i hangi amaçla kullanacaksın?</label></div><div class="authRoleGrid">${roles.map(([id,label])=>`<button type="button" data-role="${id}" class="${selected===id?'active':''}">${label}</button>`).join('')}</div></div><div id="roleDetails">${detailFields(selected,p)}</div><button class="authPrimary" type="submit">Profili Kaydet</button></form>`);wrap.querySelectorAll('[data-role]').forEach(btn=>btn.onclick=()=>{selected=btn.dataset.role;wrap.querySelectorAll('[data-role]').forEach(x=>x.classList.toggle('active',x===btn));wrap.querySelector('#roleDetails').innerHTML=detailFields(selected,p)});wrap.querySelector('#profileForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const next={name:String(fd.get('name')||'').trim()||'Kullanıcı',role:selected,detail:String(fd.get('detail')||'').trim(),secondary:String(fd.get('secondary')||'').trim(),updatedAt:Date.now()};writeJson(PROFILE_KEY,next);closeBackdrop();renderEntry()}}
function openAccountMenu(button){closeMenu();const rect=button.getBoundingClientRect();menuEl=document.createElement('div');menuEl.className='authMenu';menuEl.style.top=`${Math.min(innerHeight-210,rect.bottom+8)}px`;menuEl.style.right=`${Math.max(10,innerWidth-rect.right)}px`;menuEl.innerHTML=`<button data-action="profile">👤 Profilim</button><button data-action="errors">📕 Hata Kitapçığım</button><button data-action="level">🎯 Seviye sonuçlarım</button><button class="danger" data-action="logout">Çıkış yap</button>`;document.body.appendChild(menuEl);menuEl.querySelector('[data-action="profile"]').onclick=()=>{closeMenu();openProfileSetup()};menuEl.querySelector('[data-action="errors"]').onclick=()=>{closeMenu();[...document.querySelectorAll('button')].find(b=>(b.textContent||'').includes('Hata Kitapçığı'))?.click()};menuEl.querySelector('[data-action="level"]').onclick=()=>{closeMenu();[...document.querySelectorAll('button')].find(b=>(b.textContent||'').includes('Seviyemi Belirle'))?.click()};menuEl.querySelector('[data-action="logout"]').onclick=logout}
function logout(){closeMenu();currentUser=null;removeKey(SESSION_KEY);removeKey(PROFILE_KEY);renderEntry()}

document.addEventListener('click',e=>{if(menuEl&&!menuEl.contains(e.target)&&!e.target.closest?.('.authEntry'))closeMenu()});
const observer=new MutationObserver(enhanceHeader);observer.observe(document.documentElement,{childList:true,subtree:true});
restore();
