const SUPABASE_URL=(import.meta.env.VITE_SUPABASE_URL||'').trim().replace(/\/+$/,'');
const SUPABASE_ANON_KEY=(import.meta.env.VITE_SUPABASE_ANON_KEY||'').trim();
const SESSION_KEY='nesevren-auth-session-v1';
const PROFILE_KEY='nesevren-user-profile-v1';
const configured=Boolean(SUPABASE_URL&&SUPABASE_ANON_KEY);
let currentUser=null;
let menuEl=null;

const GOOGLE_ICON=`<svg viewBox="0 0 24 24" role="img" aria-hidden="true" focusable="false"><path fill="#4285F4" d="M21.35 12.22c0-.74-.06-1.29-.2-1.86H12v3.42h5.37c-.11.85-.71 2.13-2.05 2.99l-.02.11 2.98 2.31.21.02c1.92-1.77 3.03-4.38 3.03-7.49 0-.72-.06-1.4-.17-2.05Z"/><path fill="#34A853" d="M12 21.4c2.75 0 5.05-.9 6.73-2.45l-3.3-2.55c-.88.6-2.07 1.03-3.43 1.03-2.62 0-4.84-1.77-5.64-4.15l-.11.01-3.24 2.51-.04.1A10.17 10.17 0 0 0 12 21.4Z"/><path fill="#FBBC05" d="M6.36 13.28A6.12 6.12 0 0 1 6.04 12c0-.45.08-.89.22-1.31l-.01-.11-3.28-2.55-.1.05A9.43 9.43 0 0 0 2 12c0 1.42.34 2.76.97 3.92l3.39-2.64Z"/><path fill="#EA4335" d="M12 6.57c1.9 0 3.18.82 3.91 1.5l2.85-2.78C17.01 3.66 14.72 2.6 12 2.6a10.17 10.17 0 0 0-9.03 5.48l3.39 2.61C7.16 8.31 9.38 6.57 12 6.57Z"/></svg>`;
const APPLE_ICON=`<svg viewBox="0 0 24 24" role="img" aria-hidden="true" focusable="false"><path fill="currentColor" d="M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47-1.32.03-1.75-.79-3.27-.79-1.53 0-2 .76-3.25.82-1.3.05-2.29-1.32-3.13-2.54C4.31 17 3 12.5 4.71 9.53c.84-1.47 2.35-2.4 3.98-2.43 1.24-.02 2.42.84 3.18.84.75 0 2.16-1.04 3.64-.89.62.03 2.35.25 3.47 1.88-.09.06-2.07 1.22-2.05 3.74.03 3.02 2.65 4.03 2.68 4.04-.03.07-.42 1.44-1.4 2.79ZM13 3.5c.7-.8 1.86-1.4 2.91-1.5.14 1.16-.34 2.32-1 3.15-.65.84-1.72 1.5-2.78 1.42-.16-1.14.38-2.32.87-3.07Z"/></svg>`;

function readJson(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
function writeJson(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function removeKey(key){try{localStorage.removeItem(key)}catch{}}
function closeBackdrop(){document.querySelector('.authBackdrop')?.remove()}
function closeMenu(){menuEl?.remove();menuEl=null}
function initials(name=''){const p=name.trim().split(/\s+/).filter(Boolean);return (p[0]?.[0]||'K')+(p[1]?.[0]||'')}
function profile(){return readJson(PROFILE_KEY)||null}
function session(){return readJson(SESSION_KEY)||null}
function displayName(){const p=profile();return p?.name||currentUser?.user_metadata?.full_name||currentUser?.user_metadata?.name||currentUser?.email||currentUser?.phone||'Profil'}
function authHeaders(token=SUPABASE_ANON_KEY){return{'Content-Type':'application/json','apikey':SUPABASE_ANON_KEY,'Authorization':`Bearer ${token}`}}
function unavailableMessage(){return'Giriş hizmeti henüz etkinleştirilmedi. Yapılandırma tamamlandığında Google, Apple ve telefonla giriş kullanılabilir.'}

async function fetchUser(accessToken){if(!configured||!accessToken)return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:authHeaders(accessToken)});if(!r.ok)return null;return await r.json()}
async function restore(){const hash=new URLSearchParams(location.hash.replace(/^#/,''));const access=hash.get('access_token');if(access){const s={access_token:access,refresh_token:hash.get('refresh_token')||'',expires_at:Date.now()+Number(hash.get('expires_in')||3600)*1000};writeJson(SESSION_KEY,s);history.replaceState(null,'',location.pathname+location.search)}const s=session();if(s?.access_token)currentUser=await fetchUser(s.access_token);enhanceHeader();if(currentUser&&!profile())setTimeout(openProfileSetup,120)}
function enhanceHeader(){const status=document.querySelector('.appTopbar .aiStatus');if(!status)return;if(status.dataset.authReady==='1')return;status.dataset.authReady='1';status.className='authEntry';status.innerHTML='';status.type='button';status.addEventListener('click',e=>{e.preventDefault();closeMenu();if(currentUser)openAccountMenu(status);else openLogin()});renderEntry(status)}
function renderEntry(button=document.querySelector('.appTopbar .authEntry')){if(!button)return;if(currentUser){const name=displayName();button.innerHTML=`<span class="authAvatar">${initials(name).toUpperCase()}</span><span>${escapeHtml(name.length>18?name.slice(0,16)+'…':name)}</span>`}else button.innerHTML='<span class="authAvatar">👤</span><span>Giriş Yap</span>'}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function modalShell(title,description,content){closeBackdrop();const wrap=document.createElement('div');wrap.className='authBackdrop';wrap.innerHTML=`<section class="authModal" role="dialog" aria-modal="true" aria-label="${escapeHtml(title)}"><button class="authClose" type="button" aria-label="Kapat">×</button><div class="authHead"><h2>${title}</h2><p>${description}</p></div>${content}</section>`;document.body.appendChild(wrap);wrap.querySelector('.authClose').onclick=closeBackdrop;wrap.addEventListener('click',e=>{if(e.target===wrap)closeBackdrop()});return wrap}
function providerButton(provider,label,icon){return`<button class="authProvider" type="button" data-provider="${provider}" aria-label="${label}"><span class="authProviderIcon">${icon}</span><span class="authProviderLabel">${label}</span></button>`}
function openLogin(){const wrap=modalShell('Neşevren’e giriş yap','Hesabınla giriş yaptığında öğrenme geçmişin ve kişisel profilin aynı kullanıcıyla eşleştirilir.',`<div class="authProviders">${providerButton('google','Google ile devam et',GOOGLE_ICON)}${providerButton('apple','Apple ile devam et',APPLE_ICON)}</div><div class="authDivider"><span>veya</span></div><div class="authPhone"><div class="authField"><label for="authPhone">Cep telefonu</label><div class="authPhoneInput"><span class="authCountry" aria-hidden="true">🇹🇷</span><input id="authPhone" type="tel" inputmode="tel" placeholder="+90 5xx xxx xx xx" autocomplete="tel"></div></div><button class="authPrimary" id="sendOtp" type="button">Telefonla devam et</button></div><div id="authMsg" aria-live="polite"></div>`);wrap.querySelectorAll('[data-provider]').forEach(btn=>btn.addEventListener('click',()=>startOAuth(btn.dataset.provider,wrap)));wrap.querySelector('#sendOtp').onclick=()=>sendOtp(wrap);setTimeout(()=>wrap.querySelector('#authPhone')?.focus(),80)}
function startOAuth(provider,wrap){if(!configured){setMsg(wrap,unavailableMessage(),true);return}const redirect=location.origin+location.pathname;location.assign(`${SUPABASE_URL}/auth/v1/authorize?provider=${encodeURIComponent(provider)}&redirect_to=${encodeURIComponent(redirect)}`)}
function normalizePhone(v){let s=v.replace(/[^+\d]/g,'');if(s.startsWith('0'))s='+90'+s.slice(1);if(/^5\d{9}$/.test(s))s='+90'+s;return s}
async function sendOtp(wrap){if(!configured){setMsg(wrap,unavailableMessage(),true);return}const input=wrap.querySelector('#authPhone');const phone=normalizePhone(input.value.trim());if(!/^\+\d{10,15}$/.test(phone)){setMsg(wrap,'Telefon numarasını ülke koduyla yazın. Örnek: +90 5xx xxx xx xx',true);return}setMsg(wrap,'Doğrulama kodu gönderiliyor…');try{const r=await fetch(`${SUPABASE_URL}/auth/v1/otp`,{method:'POST',headers:authHeaders(),body:JSON.stringify({phone,create_user:true})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.msg||data?.message||'Kod gönderilemedi.');showOtpVerify(wrap,phone)}catch(e){setMsg(wrap,e.message||'Kod gönderilemedi.',true)}}
function showOtpVerify(wrap,phone){const phoneBox=wrap.querySelector('.authPhone');phoneBox.innerHTML=`<div class="authField"><label for="authOtp">${escapeHtml(phone)} numarasına gelen kod</label><input id="authOtp" type="text" inputmode="numeric" maxlength="8" placeholder="Doğrulama kodu" autocomplete="one-time-code"></div><button class="authPrimary" id="verifyOtp" type="button">Kodu doğrula</button><button class="authSecondary" id="changePhone" type="button">Numarayı değiştir</button>`;phoneBox.querySelector('#verifyOtp').onclick=()=>verifyOtp(wrap,phone);phoneBox.querySelector('#changePhone').onclick=openLogin;setMsg(wrap,'SMS doğrulama kodunu girin.');setTimeout(()=>phoneBox.querySelector('#authOtp')?.focus(),60)}
async function verifyOtp(wrap,phone){const token=wrap.querySelector('#authOtp')?.value.trim();if(!token){setMsg(wrap,'Doğrulama kodunu yazın.',true);return}setMsg(wrap,'Kod doğrulanıyor…');try{const r=await fetch(`${SUPABASE_URL}/auth/v1/verify`,{method:'POST',headers:authHeaders(),body:JSON.stringify({type:'sms',phone,token})});const data=await r.json().catch(()=>({}));if(!r.ok||!data.access_token)throw new Error(data?.msg||data?.message||'Kod doğrulanamadı.');writeJson(SESSION_KEY,{access_token:data.access_token,refresh_token:data.refresh_token||'',expires_at:Date.now()+(data.expires_in||3600)*1000});currentUser=data.user||await fetchUser(data.access_token);closeBackdrop();renderEntry();if(!profile())openProfileSetup()}catch(e){setMsg(wrap,e.message||'Kod doğrulanamadı.',true)}}
function setMsg(wrap,text,isError=false){const el=wrap.querySelector('#authMsg');if(!el)return;el.className=`authMessage${isError?' error':''}`;el.textContent=text}

const roles=[['student','🎓 Öğrenci'],['teacher','👩‍🏫 Öğretmen / Eğitmen'],['parent','👨‍👩‍👧 Veli'],['professional','💼 Profesyonel / Çalışan'],['business','🏢 İşletme sahibi / Girişimci'],['other','◌ Diğer']];
function detailFields(role,p={}){if(role==='student')return `<div class="authField"><label>Sınıf / seviye</label><input name="detail" value="${escapeHtml(p.detail||'')}" placeholder="Örn. 8. sınıf, TYT, üniversite"></div><div class="authField"><label>İlgilendiğin dersler</label><input name="secondary" value="${escapeHtml(p.secondary||'')}" placeholder="Örn. Matematik, Fizik, İngilizce"></div>`;if(role==='teacher')return `<div class="authField"><label>Branş / uzmanlık</label><input name="detail" value="${escapeHtml(p.detail||'')}" placeholder="Örn. Matematik öğretmeni"></div><div class="authField"><label>Çalıştığın seviye</label><input name="secondary" value="${escapeHtml(p.secondary||'')}" placeholder="Örn. Ortaokul, lise, YKS"></div>`;if(role==='parent')return `<div class="authField"><label>Öğrencinin sınıfı / seviyesi</label><input name="detail" value="${escapeHtml(p.detail||'')}" placeholder="Örn. 6. sınıf"></div>`;if(role==='business')return `<div class="authField"><label>Sektör / iş alanı</label><input name="detail" value="${escapeHtml(p.detail||'')}" placeholder="Örn. eğitim, perakende, inşaat"></div>`;if(role==='professional')return `<div class="authField"><label>Meslek / uzmanlık alanı</label><input name="detail" value="${escapeHtml(p.detail||'')}" placeholder="Örn. mühendis, muhasebeci, yazılımcı"></div>`;return `<div class="authField"><label>Kullanım amacın</label><input name="detail" value="${escapeHtml(p.detail||'')}" placeholder="Kısaca yazabilirsin"></div>`}
function openProfileSetup(){const p=profile()||{};let selected=p.role||'student';const suggested=currentUser?.user_metadata?.full_name||currentUser?.user_metadata?.name||'';const wrap=modalShell('Profilini tamamla','Neşevren içeriği ve önerileri sana daha uygun hale getirmek için birkaç kısa bilgi ister.',`<form class="authProfileForm" id="profileForm"><div class="authField"><label>Ad / görünen ad</label><input name="name" value="${escapeHtml(p.name||suggested)}" placeholder="Adın"></div><div><div class="authField"><label>Neşevren’i hangi amaçla kullanacaksın?</label></div><div class="authRoleGrid">${roles.map(([id,label])=>`<button type="button" data-role="${id}" class="${selected===id?'active':''}">${label}</button>`).join('')}</div></div><div id="roleDetails">${detailFields(selected,p)}</div><button class="authPrimary" type="submit">Profili Kaydet</button></form>`);wrap.querySelectorAll('[data-role]').forEach(btn=>btn.onclick=()=>{selected=btn.dataset.role;wrap.querySelectorAll('[data-role]').forEach(x=>x.classList.toggle('active',x===btn));wrap.querySelector('#roleDetails').innerHTML=detailFields(selected,p)});wrap.querySelector('#profileForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const next={name:String(fd.get('name')||'').trim()||'Kullanıcı',role:selected,detail:String(fd.get('detail')||'').trim(),secondary:String(fd.get('secondary')||'').trim(),updatedAt:Date.now()};writeJson(PROFILE_KEY,next);closeBackdrop();renderEntry()}}
function openAccountMenu(button){closeMenu();const rect=button.getBoundingClientRect();menuEl=document.createElement('div');menuEl.className='authMenu';menuEl.style.top=`${Math.min(innerHeight-210,rect.bottom+8)}px`;menuEl.style.right=`${Math.max(10,innerWidth-rect.right)}px`;menuEl.innerHTML=`<button data-action="profile">👤 Profilim</button><button data-action="errors">📕 Hata Kitapçığım</button><button data-action="level">🎯 Seviye sonuçlarım</button><button class="danger" data-action="logout">Çıkış yap</button>`;document.body.appendChild(menuEl);menuEl.querySelector('[data-action="profile"]').onclick=()=>{closeMenu();openProfileSetup()};menuEl.querySelector('[data-action="errors"]').onclick=()=>{closeMenu();[...document.querySelectorAll('button')].find(b=>(b.textContent||'').includes('Hata Kitapçığı'))?.click()};menuEl.querySelector('[data-action="level"]').onclick=()=>{closeMenu();[...document.querySelectorAll('button')].find(b=>(b.textContent||'').includes('Seviyemi Belirle'))?.click()};menuEl.querySelector('[data-action="logout"]').onclick=logout}
function logout(){closeMenu();currentUser=null;removeKey(SESSION_KEY);removeKey(PROFILE_KEY);renderEntry()}

document.addEventListener('click',e=>{if(menuEl&&!menuEl.contains(e.target)&&!e.target.closest?.('.authEntry'))closeMenu()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeBackdrop()});
const observer=new MutationObserver(enhanceHeader);observer.observe(document.documentElement,{childList:true,subtree:true});
restore();
