let voiceRecognition=null;
let voiceListening=false;
let voiceSilenceTimer=null;
let voiceHasCaptured=false;
let voiceSoundActive=false;
let voiceButtonRef=null;

function findQuickButton(label){return [...document.querySelectorAll('.quickActions button')].find(b=>(b.textContent||'').includes(label))}
function questionTextarea(){return document.querySelector('.questionBox textarea')}
function setReactTextareaValue(textarea,value){if(!textarea)return;const setter=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')?.set;if(setter)setter.call(textarea,value);else textarea.value=value;textarea.dispatchEvent(new Event('input',{bubbles:true}))}
function clearVoiceTimer(){if(voiceSilenceTimer){clearTimeout(voiceSilenceTimer);voiceSilenceTimer=null}}
function armSilenceTimer(){clearVoiceTimer();if(!voiceListening||voiceSoundActive)return;voiceSilenceTimer=setTimeout(()=>stopVoice('silence'),3000)}
function setVoiceButtonState(mode){const button=voiceButtonRef||document.querySelector('.composerVoiceButton');if(!button)return;voiceButtonRef=button;button.classList.toggle('voiceListening',mode==='listening');button.classList.toggle('voicePaused',mode==='paused');button.setAttribute('aria-pressed',mode==='listening'?'true':'false');if(mode==='listening'){button.innerHTML='<span>🔴</span><b>Dinliyorum</b>';button.title='Durdurmak için tekrar dokun';return}if(mode==='paused'){button.innerHTML='<span>🎙️</span><b>Devam Et</b>';button.title='Kaldığın yerden sesli soruya devam et';return}button.innerHTML='<span>🎙️</span><b>Sesli Sor</b>';button.title='Sesli soru sor'}
function finishVoiceUi(){const textarea=questionTextarea();setVoiceButtonState(voiceHasCaptured&&Boolean(textarea?.value.trim())?'paused':'idle')}
function stopVoice(reason='manual'){if(!voiceListening){finishVoiceUi();return}voiceListening=false;voiceSoundActive=false;clearVoiceTimer();const current=voiceRecognition;voiceRecognition=null;try{current?.stop()}catch{}finishVoiceUi();if(reason==='silence'){const button=voiceButtonRef;if(button){button.dataset.stopReason='silence';setTimeout(()=>{if(button.dataset.stopReason==='silence')delete button.dataset.stopReason},1500)}}}
function startVoiceCapture(){if(voiceListening){stopVoice('manual');return}const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){alert('Bu tarayıcı sesli soru özelliğini desteklemiyor. Chrome ile tekrar deneyebilirsiniz.');return}const textarea=questionTextarea();if(!textarea)return;const base=textarea.value.trim();const basePrefix=base?`${base} `:'';let finalText='';let interimText='';let recognition;try{recognition=new Speech()}catch{alert('Mikrofon başlatılamadı. Tarayıcı mikrofon iznini kontrol edin.');return}voiceRecognition=recognition;voiceListening=true;voiceSoundActive=false;setVoiceButtonState('listening');recognition.lang='tr-TR';recognition.continuous=true;recognition.interimResults=true;recognition.maxAlternatives=1;recognition.onstart=()=>{if(!voiceListening)return;setVoiceButtonState('listening');armSilenceTimer()};recognition.onsoundstart=()=>{if(!voiceListening)return;voiceSoundActive=true;clearVoiceTimer()};recognition.onspeechstart=()=>{if(!voiceListening)return;voiceSoundActive=true;clearVoiceTimer()};recognition.onsoundend=()=>{if(!voiceListening)return;voiceSoundActive=false;armSilenceTimer()};recognition.onspeechend=()=>{if(!voiceListening)return;voiceSoundActive=false;armSilenceTimer()};recognition.onresult=e=>{if(!voiceListening)return;finalText='';interimText='';for(let i=0;i<e.results.length;i++){const transcript=e.results[i]?.[0]?.transcript||'';if(e.results[i].isFinal)finalText+=`${transcript} `;else interimText+=transcript}const spoken=`${finalText}${interimText}`.trim();if(spoken){voiceHasCaptured=true;setReactTextareaValue(textarea,`${basePrefix}${spoken}`.trim())}if(!voiceSoundActive)armSilenceTimer()};recognition.onerror=e=>{const code=e?.error||'';if(code==='aborted'&&!voiceListening)return;voiceListening=false;voiceSoundActive=false;clearVoiceTimer();voiceRecognition=null;finishVoiceUi();if(code&&code!=='no-speech'&&code!=='aborted')alert('Ses algılanamadı. Mikrofon iznini ve bağlantını kontrol edip tekrar deneyebilirsin.')};recognition.onend=()=>{if(voiceRecognition===recognition)voiceRecognition=null;if(voiceListening){voiceListening=false;voiceSoundActive=false;clearVoiceTimer();finishVoiceUi()}};try{recognition.start()}catch{voiceListening=false;voiceRecognition=null;finishVoiceUi();alert('Mikrofon başlatılamadı. Lütfen tekrar deneyin.')}}

function ensureComposerTools(){const actions=document.querySelector('.questionBox .composerActions');if(!actions)return;if(actions.querySelector('.composerInlineTools'))return;const solve=actions.querySelector('.solveButton');if(!solve)return;const wrap=document.createElement('div');wrap.className='composerInlineTools';const photo=document.createElement('button');photo.type='button';photo.className='composerToolButton composerPhotoButton';photo.innerHTML='<span>📷</span><b>Fotoğraf</b>';photo.addEventListener('click',()=>findQuickButton('Fotoğrafla Sor')?.click());const voice=document.createElement('button');voice.type='button';voice.className='composerToolButton composerVoiceButton';voice.innerHTML='<span>🎙️</span><b>Sesli Sor</b>';voice.setAttribute('aria-pressed','false');voice.addEventListener('click',()=>{if(voiceListening)stopVoice('manual')});voiceButtonRef=voice;wrap.append(photo,voice);actions.insertBefore(wrap,solve)}
function updateBrandSubtitle(){const subtitle=document.querySelector('.brandMark small');if(subtitle&&subtitle.textContent?.includes('Matematik'))subtitle.textContent="Neş'eli Yapay Zekâ Öğrenme Asistanı"}
function refreshUi(){ensureComposerTools();updateBrandSubtitle();if(voiceButtonRef&&!document.contains(voiceButtonRef)){voiceButtonRef=null;finishVoiceUi()}}
document.addEventListener('nesevren:voice-permitted',()=>startVoiceCapture());
const observer=new MutationObserver(()=>refreshUi());observer.observe(document.documentElement,{childList:true,subtree:true});refreshUi();
