import React, { useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { PhotoCropper, type Crop } from "./PhotoCropper";
import { SolutionResult } from "./SolutionResult";
import type { SolveResponse } from "./types";
import "./styles.css";
import "./hint.css";

const configuredApiUrl=(import.meta.env.VITE_API_URL??"").trim().replace(/\/+$/,"");
const API_URL=!configuredApiUrl||configuredApiUrl==="https://nesevren-api.onrender.com"?"https://nesevren-api-v2.onrender.com":configuredApiUrl;
const subjects=["Otomatik","Matematik","Fen Bilimleri","Fizik","Kimya","Biyoloji","Türkçe","Türk Dili ve Edebiyatı","İngilizce","Kürtçe","Sosyal Bilgiler","Tarih","Coğrafya","Felsefe"];

function App(){
 const [question,setQuestion]=useState(""); const [subject,setSubject]=useState("Otomatik"); const [showSubject,setShowSubject]=useState(false); const [result,setResult]=useState<SolveResponse|null>(null); const [hintText,setHintText]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const [hintLoading,setHintLoading]=useState(false); const [teacherOpen,setTeacherOpen]=useState(false); const [photoName,setPhotoName]=useState(""); const [photoPreview,setPhotoPreview]=useState(""); const [originalPhoto,setOriginalPhoto]=useState(""); const [cropSource,setCropSource]=useState(""); const [lastCrop,setLastCrop]=useState<Crop|undefined>(); const photoInput=useRef<HTMLInputElement>(null); const questionInput=useRef<HTMLTextAreaElement>(null);
 const subjectLabel=subject==="Otomatik"?"Dersi AI algılar":subject;
 async function requestAI(intent:"solve"|"hint"){const value=question.trim();if(!value&&!photoPreview){setError("Lütfen sorunuzu yazın veya bir soru fotoğrafı seçin.");return null;}const isImageQuestion=Boolean(photoPreview);const subjectInstruction=subject==="Otomatik"?"Önce sorunun hangi derse ait olduğunu kendin belirle. Ders, konu ve seviyeyi içerikten çıkar.":`Ders: ${subject}.`;const enriched=`${subjectInstruction} Öğrencinin seviyesine uygun, kavramsal anlamayı ve çözüm mantığını öne çıkaran açık, öğretici ve adım adım bir anlatım kullan. ${value}`.trim();const response=await fetch(`${API_URL}/api/v1/questions/analyze`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:enriched,inputType:isImageQuestion?"image":"text",intent,...(isImageQuestion?{imageDataUrl:photoPreview}:{})})});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error?.message??`Yapay zekâ servisi ${response.status} hatası döndürdü.`);return data as SolveResponse;}
 async function submitQuestion(){setLoading(true);setError("");setHintText("");setResult(null);try{const data=await requestAI("solve");if(data)setResult(data);}catch(e){setError(e instanceof Error?e.message:"Beklenmeyen bir hata oluştu.");}finally{setLoading(false)}}
 async function requestHint(){setHintLoading(true);setError("");setHintText("");try{const data=await requestAI("hint");const hint=data?.finalAnswer?.hint||data?.answer?.hint||data?.finalAnswer?.explanation||data?.answer?.explanation;if(!hint)throw new Error("Bu soru için ipucu üretilemedi.");setHintText(hint);}catch(e){setError(e instanceof Error?e.message:"İpucu hazırlanamadı.");}finally{setHintLoading(false)}}
 function choosePhoto(){photoInput.current?.click()} function onPhotoChange(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith("image/")){setError("Lütfen galeriden veya dosyalardan bir fotoğraf seçin.");return}if(file.size>8*1024*1024){setError("Fotoğraf en fazla 8 MB olabilir.");return}if(originalPhoto.startsWith("blob:"))URL.revokeObjectURL(originalPhoto);const u=URL.createObjectURL(file);setPhotoName(file.name);setOriginalPhoto(u);setCropSource(u);setLastCrop(undefined);setPhotoPreview("");setResult(null);setHintText("");setError("");e.target.value=""} function applyCrop(dataUrl:string,crop:Crop){setPhotoPreview(dataUrl);setLastCrop(crop);setCropSource("");setHintText("");setError("")} function editCropAgain(){if(originalPhoto)setCropSource(originalPhoto)}
 return <main className="shell appShell"><section className="hero appHero">
 <header className="appTopbar"><div className="brandMark"><span className="brandOrb">N</span><div><strong>Neşevren</strong><small>Neş'eli Matematik • Yapay Zekâ Öğrenme Asistanı</small></div></div><span className="aiStatus">● Hazır</span></header>
 <div className="aiHero"><div className="aiGlow">✦</div><div><h1>Sorunu gönder.<br/>Dersi ben anlayayım.</h1><p>Fotoğraf, yazı veya ses. Neşevren içeriği analiz eder, dersi ve konuyu algılar.</p></div></div>
 <div className="quickActions compactQuick"><button className="quickAction primaryQuick" onClick={choosePhoto}><span>📷</span><strong>Fotoğrafla Sor</strong><small>Çek veya galeriden seç</small></button><button className="quickAction" onClick={()=>questionInput.current?.focus()}><span>✍️</span><strong>Yazarak Sor</strong><small>Sorunu doğrudan yaz</small></button><button className="quickAction" disabled><span>🎙️</span><strong>Sesli Sor</strong><small>Yakında</small></button></div>
 <div className="subjectAssist"><button type="button" onClick={()=>setShowSubject(v=>!v)}>🤖 {subjectLabel} <span>{showSubject?"⌃":"⌄"}</span></button>{showSubject&&<div className="subjectInline"><label htmlFor="subject">İstersen dersi elle seç</label><select id="subject" value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s}>{s}</option>)}</select></div>}</div>
 <div className="questionBox modernQuestionBox"><div className="composerTitle"><strong>✦ Neşevren'e sor</strong><span>{subjectLabel}</span></div><textarea ref={questionInput} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Sorunu buraya yaz veya fotoğraf ekle..." rows={4}/>{photoPreview&&<div className="photoPreview"><img src={photoPreview} alt="Kırpılmış soru fotoğrafı"/><div className="photoPreviewFooter"><span>{photoName}</span><button type="button" className="secondary" onClick={editCropAgain}>✂️ Kırpmayı düzenle</button></div></div>}<input ref={photoInput} type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={onPhotoChange} style={{display:"none"}}/><div className="composerActions"><button className="attachButton" onClick={choosePhoto}>＋ Fotoğraf</button><button className="solveButton" onClick={submitQuestion} disabled={loading||hintLoading}>{loading?"Analiz ediyorum…":"Çöz →"}</button></div></div>
 <button className="teacherStrip" onClick={()=>setTeacherOpen(true)}><span>👩‍🏫</span><div><strong>Canlı öğretmen ister misin?</strong><small>Sorunu kayıtlı branş öğretmenine gönder.</small></div><b>→</b></button>
 {loading&&<div className="thinking"><span>✦</span><div><strong>Neşevren analiz ediyor…</strong><small>Ders, konu ve çözüm yolunu belirliyorum.</small></div></div>}{hintLoading&&<div className="thinking"><span>💡</span><div><strong>İpucu hazırlanıyor…</strong><small>Cevabı söylemeden doğru adıma yönlendiriyorum.</small></div></div>}{error&&<div className="errorBox">{error}</div>}{hintText&&<div className="aiHintCard"><div className="aiHintIcon">💡</div><div><span>İPUCU AI</span><strong>Cevabı vermeden küçük bir yönlendirme</strong><p>{hintText}</p></div></div>}{result&&<SolutionResult result={result}/>}</section>
 <section className="cards featureCards"><button className="featureAction" onClick={requestHint} disabled={loading||hintLoading}><span className="featureIcon">💡</span><strong>İpucu Al</strong><span>Cevabı görmeden doğru adıma yönel.</span></button><button className="featureAction" disabled><span className="featureIcon">📝</span><strong>Benzer Soru</strong><span>Öğrendiğini yeni bir soruyla pekiştir.</span></button><button className="featureAction" disabled><span className="featureIcon">✓</span><strong>Doğrula</strong><span>Çözümünü kontrol et.</span></button></section>
 <nav className="bottomNav"><button className="active">⌂<small>Ana Sayfa</small></button><button onClick={choosePhoto}>▣<small>Soru Sor</small></button><button disabled>▤<small>Dersler</small></button><button disabled>○<small>Profil</small></button></nav>
 {teacherOpen&&<div className="teacherModalBackdrop" onClick={()=>setTeacherOpen(false)}><div className="teacherModal" onClick={e=>e.stopPropagation()}><button className="teacherClose" onClick={()=>setTeacherOpen(false)}>×</button><span className="teacherBigIcon">👩‍🏫</span><h2>Canlı Öğretmen Çözümü</h2><p>Sorunuz kayıtlı branş öğretmenlerimize yönlendirilecek. Neşevren dersi otomatik algılayabilir; isterseniz yukarıdan elle de seçebilirsiniz.</p><button className="solveButton" onClick={()=>{setTeacherOpen(false);choosePhoto()}}>Soruyu Hazırla</button></div></div>}
 {cropSource&&<PhotoCropper src={cropSource} initialCrop={lastCrop} onCancel={()=>setCropSource("")} onApply={applyCrop}/>}</main>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
