import { buildPerformanceSummary, createPerformanceRecord, wrongPenalty } from "./performance-tracker.ts";

const configuredApiUrl=(import.meta.env.VITE_API_URL??"").trim().replace(/\/+$/,"");
const API_URL=!configuredApiUrl||configuredApiUrl==="https://nesevren-api.onrender.com"?"https://nesevren-api-v2.onrender.com":configuredApiUrl;
const PERFORMANCE_KEY="nesevren-performance-records";
const TASKS_KEY="nesevren-coach-tasks";
const examTypes=["LGS","TYT","AYT","KPSS","ALES","Genel"];
const subjectNames=["Matematik","Fen Bilimleri","Fizik","Kimya","Biyoloji","Türkçe","Türk Dili ve Edebiyatı","İngilizce","Kürtçe","Arapça","Sosyal Bilgiler","Tarih","Coğrafya","Felsefe"];

function readJson(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function writeJson(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function performanceRecords(){const value=readJson(PERFORMANCE_KEY,[]);return Array.isArray(value)?value:[]}
function today(){const d=new Date();const m=String(d.getMonth()+1).padStart(2,"0");const day=String(d.getDate()).padStart(2,"0");return`${d.getFullYear()}-${m}-${day}`}
function formatNumber(value){if(value===null||value===undefined||!Number.isFinite(Number(value)))return"—";return Number(value).toLocaleString("tr-TR",{maximumFractionDigits:2})}
function formatDate(value){if(!value)return"—";const d=new Date(`${value}T12:00:00`);return Number.isNaN(d.getTime())?value:d.toLocaleDateString("tr-TR",{day:"2-digit",month:"short"})}
function trendText(value){if(value===null)return"İlk kayıt";if(value>0)return`▲ +${formatNumber(value)}`;if(value<0)return`▼ ${formatNumber(value)}`;return"● Değişmedi"}
function isVisible(node){return node&&node.getClientRects().length>0}

function sectionMarkup(){return`<section class="coachSection performanceSection" id="performanceSection">
  <div class="coachSectionHead"><div><h3>📈 Deneme & Performans</h3><small>Net, süre, ders ve konu gelişimini tek yerde izle</small></div><span class="performanceRule" id="performanceRule">4 yanlış = 1 doğru</span></div>
  <div class="performanceStats">
    <div><strong id="performanceLatestNet">—</strong><span>Son net</span></div>
    <div><strong id="performanceChange">—</strong><span>Net değişimi</span></div>
    <div><strong id="performanceBest">—</strong><span>En iyi net</span></div>
    <div><strong id="performanceAvgTime">—</strong><span>Ort. süre</span></div>
  </div>
  <div class="performanceChartWrap"><div class="performanceChartHead"><strong>Net gelişimi</strong><small id="performanceChartNote">Henüz deneme kaydı yok</small></div><div id="performanceChart" class="performanceChart"></div></div>
  <details class="performanceEntry" open><summary>＋ Yeni deneme sonucu ekle</summary>
    <div class="performanceFormGrid">
      <label>Sınav türü<select id="performanceExam">${examTypes.map(type=>`<option>${type}</option>`).join("")}</select></label>
      <label>Deneme adı<input id="performanceName" placeholder="Örn. TYT Türkiye Geneli 1"/></label>
      <label>Tarih<input id="performanceDate" type="date" value="${today()}"/></label>
      <label>Süre (dk)<input id="performanceDuration" type="number" min="1" max="600" placeholder="120"/></label>
    </div>
    <div class="performanceResultsHead"><strong>Ders / konu sonuçları</strong><small>Her satıra doğru, yanlış ve boş sayılarını gir.</small></div>
    <datalist id="performanceSubjects">${subjectNames.map(subject=>`<option value="${subject}"></option>`).join("")}</datalist>
    <div id="performanceRows" class="performanceRows"></div>
    <div class="performanceFormActions"><button id="performanceAddRow" class="coachSecondary" type="button">＋ Ders ekle</button><button id="performanceSave" class="coachPrimary" type="button">Denemeyi Kaydet</button></div>
    <div id="performanceFormMessage"></div>
  </details>
  <div class="performanceSplit">
    <div><div class="performanceSubhead"><strong>Ders / konu gelişimi</strong><small>Son sonuç ve önceki denemeye göre değişim</small></div><div id="performanceAreas" class="performanceAreas"></div></div>
    <div><div class="performanceSubhead"><strong>Son denemeler</strong><small>Kayıtları karşılaştır veya sil</small></div><div id="performanceHistory" class="performanceHistory"></div></div>
  </div>
  <div class="performanceAiActions"><button id="performanceAi" class="coachPrimary" type="button">✨ AI ile performansımı analiz et</button><button id="performanceTask" class="coachSecondary" type="button">🎯 Zayıf alanı görevlere ekle</button></div>
  <div id="performanceAiResult"></div>
</section>`}

function createResultRow(root,seed={}){
  const row=document.createElement("div");row.className="performanceResultRow";
  row.innerHTML='<input class="performanceSubject" list="performanceSubjects" placeholder="Ders"><input class="performanceTopic" placeholder="Konu (isteğe bağlı)"><input class="performanceCorrect" type="number" min="0" placeholder="D"><input class="performanceWrong" type="number" min="0" placeholder="Y"><input class="performanceBlank" type="number" min="0" placeholder="B"><span class="performanceRowNet">0 net</span><button class="performanceRemove" type="button" aria-label="Satırı sil">×</button>';
  row.querySelector(".performanceSubject").value=seed.subject??"";row.querySelector(".performanceTopic").value=seed.topic??"";row.querySelector(".performanceCorrect").value=seed.correct??"";row.querySelector(".performanceWrong").value=seed.wrong??"";row.querySelector(".performanceBlank").value=seed.blank??"";
  row.querySelector(".performanceRemove").addEventListener("click",()=>{if(root.querySelectorAll(".performanceResultRow").length>1)row.remove()});
  row.querySelectorAll("input").forEach(input=>input.addEventListener("input",()=>updateRowNet(root,row)));
  root.querySelector("#performanceRows").appendChild(row);updateRowNet(root,row);
}

function updateRowNet(root,row){const type=root.querySelector("#performanceExam")?.value||"Genel";const correct=Number(row.querySelector(".performanceCorrect")?.value)||0;const wrong=Number(row.querySelector(".performanceWrong")?.value)||0;const net=correct-wrong/wrongPenalty(type);row.querySelector(".performanceRowNet").textContent=`${formatNumber(Math.round(net*100)/100)} net`}

function readSubjectRows(root){return[...root.querySelectorAll(".performanceResultRow")].map(row=>({subject:row.querySelector(".performanceSubject").value.trim(),topic:row.querySelector(".performanceTopic").value.trim(),correct:Number(row.querySelector(".performanceCorrect").value)||0,wrong:Number(row.querySelector(".performanceWrong").value)||0,blank:Number(row.querySelector(".performanceBlank").value)||0})).filter(item=>item.subject&&(item.correct+item.wrong+item.blank)>0)}

function showFormMessage(root,text,error=false){const holder=root.querySelector("#performanceFormMessage");holder.textContent="";const box=document.createElement("div");box.className=error?"performanceMessage error":"performanceMessage";box.textContent=text;holder.appendChild(box);setTimeout(()=>{if(box.isConnected)box.remove()},3000)}

function savePerformance(root){const examType=root.querySelector("#performanceExam").value;const name=root.querySelector("#performanceName").value.trim();const date=root.querySelector("#performanceDate").value;const duration=Number(root.querySelector("#performanceDuration").value)||0;const subjects=readSubjectRows(root);if(!date){showFormMessage(root,"Deneme tarihini seç.",true);return}if(duration<=0){showFormMessage(root,"Deneme süresini dakika olarak yaz.",true);return}if(!subjects.length){showFormMessage(root,"En az bir ders için doğru, yanlış veya boş sonucu gir.",true);return}const record=createPerformanceRecord({examType,name,date,durationMinutes:duration,subjects});const records=performanceRecords();records.unshift(record);writeJson(PERFORMANCE_KEY,records.slice(0,120));root.querySelector("#performanceName").value="";root.querySelector("#performanceDuration").value="";root.querySelector("#performanceRows").textContent="";createResultRow(root);renderPerformance(root);showFormMessage(root,`${record.name} kaydedildi: ${formatNumber(record.totalNet)} net.`);window.dispatchEvent(new CustomEvent("nesevren-performance-updated",{detail:record}))}

function renderChart(root,summary){const holder=root.querySelector("#performanceChart");holder.textContent="";const note=root.querySelector("#performanceChartNote");if(!summary.series.length){note.textContent="Henüz deneme kaydı yok";const empty=document.createElement("div");empty.className="performanceEmpty";empty.textContent="İlk denemeni eklediğinde net gelişim grafiğin burada oluşacak.";holder.appendChild(empty);return}note.textContent=`Son ${summary.series.length} deneme`;const width=560,height=170,padX=34,padY=24;const values=summary.series.map(item=>item.totalNet);const min=Math.min(...values);const max=Math.max(...values);const spread=Math.max(1,max-min);const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("viewBox",`0 0 ${width} ${height}`);svg.setAttribute("role","img");svg.setAttribute("aria-label","Deneme net gelişim grafiği");const points=summary.series.map((item,index)=>{const x=summary.series.length===1?width/2:padX+index*(width-2*padX)/(summary.series.length-1);const y=height-padY-(item.totalNet-min)/spread*(height-2*padY);return{x,y,item}});const line=document.createElementNS(svg.namespaceURI,"polyline");line.setAttribute("points",points.map(p=>`${p.x},${p.y}`).join(" "));line.setAttribute("class","performanceLine");svg.appendChild(line);points.forEach(point=>{const circle=document.createElementNS(svg.namespaceURI,"circle");circle.setAttribute("cx",String(point.x));circle.setAttribute("cy",String(point.y));circle.setAttribute("r","5");circle.setAttribute("class","performancePoint");const title=document.createElementNS(svg.namespaceURI,"title");title.textContent=`${point.item.label}: ${formatNumber(point.item.totalNet)} net`;circle.appendChild(title);svg.appendChild(circle);const label=document.createElementNS(svg.namespaceURI,"text");label.setAttribute("x",String(point.x));label.setAttribute("y",String(height-5));label.setAttribute("text-anchor","middle");label.setAttribute("class","performanceAxisLabel");label.textContent=formatDate(point.item.date);svg.appendChild(label)});holder.appendChild(svg)}

function renderAreas(root,summary){const holder=root.querySelector("#performanceAreas");holder.textContent="";const areas=(summary.topicTrends.length?summary.topicTrends:summary.subjectTrends).slice(0,8);if(!areas.length){const empty=document.createElement("div");empty.className="performanceEmpty";empty.textContent="Ders ve konu sonuçları eklendikçe güçlü ve gelişmesi gereken alanlar burada görünecek.";holder.appendChild(empty);return}areas.forEach(area=>{const card=document.createElement("div");card.className="performanceArea";const top=document.createElement("div");const strong=document.createElement("strong");strong.textContent=area.key;const change=document.createElement("span");change.textContent=trendText(area.netChange);change.className=area.netChange===null?"":area.netChange>0?"up":area.netChange<0?"down":"";top.append(strong,change);const bar=document.createElement("div");bar.className="performanceAccuracy";const fill=document.createElement("i");fill.style.width=`${Math.max(0,Math.min(100,area.latestAccuracyPercent))}%`;bar.appendChild(fill);const meta=document.createElement("small");meta.textContent=`Son: ${formatNumber(area.latestNet)} net · Doğruluk %${area.latestAccuracyPercent} · ${area.attempts} kayıt`;card.append(top,bar,meta);holder.appendChild(card)})}

function renderHistory(root,records){const holder=root.querySelector("#performanceHistory");holder.textContent="";if(!records.length){const empty=document.createElement("div");empty.className="performanceEmpty";empty.textContent="Henüz kayıtlı deneme yok.";holder.appendChild(empty);return}records.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))||b.createdAt-a.createdAt).slice(0,10).forEach(record=>{const row=document.createElement("div");row.className="performanceHistoryRow";const body=document.createElement("div");const strong=document.createElement("strong");strong.textContent=record.name;const small=document.createElement("small");small.textContent=`${record.examType} · ${formatDate(record.date)} · ${record.durationMinutes} dk · ${record.totalCorrect}D ${record.totalWrong}Y ${record.totalBlank}B`;body.append(strong,small);const net=document.createElement("b");net.textContent=`${formatNumber(record.totalNet)} net`;const del=document.createElement("button");del.type="button";del.textContent="×";del.setAttribute("aria-label","Deneme kaydını sil");del.addEventListener("click",()=>{writeJson(PERFORMANCE_KEY,performanceRecords().filter(item=>item.id!==record.id));renderPerformance(root);window.dispatchEvent(new CustomEvent("nesevren-performance-updated"))});row.append(body,net,del);holder.appendChild(row)})}

function renderPerformance(root){const records=performanceRecords();const summary=buildPerformanceSummary(records);root.querySelector("#performanceLatestNet").textContent=formatNumber(summary.latestTotalNet);root.querySelector("#performanceChange").textContent=trendText(summary.netChange);root.querySelector("#performanceBest").textContent=formatNumber(summary.bestNet);root.querySelector("#performanceAvgTime").textContent=summary.averageDurationMinutes===null?"—":`${summary.averageDurationMinutes} dk`;root.querySelector("#performanceRule").textContent=root.querySelector("#performanceExam")?.value==="LGS"?"3 yanlış = 1 doğru":"4 yanlış = 1 doğru";renderChart(root,summary);renderAreas(root,summary);renderHistory(root,records);const task=root.querySelector("#performanceTask");if(task)task.disabled=!summary.weakestArea;window.NesevrenPerformance={records:()=>performanceRecords(),summary:()=>buildPerformanceSummary(performanceRecords())}}

function addWeakAreaTask(root){const summary=buildPerformanceSummary(performanceRecords());const area=summary.weakestArea;if(!area){showFormMessage(root,"Göreve çevrilecek performans verisi henüz yok.",true);return}const title=`${area.key} performans çalışması`;const tasks=readJson(TASKS_KEY,[]);if(Array.isArray(tasks)&&tasks.some(item=>!item.done&&String(item.title).toLocaleLowerCase("tr-TR")===title.toLocaleLowerCase("tr-TR"))){showFormMessage(root,"Bu performans görevi zaten görev listende.");return}const next=Array.isArray(tasks)?tasks:[];next.unshift({id:`performance-${Date.now()}`,title,due:"",done:false,createdAt:Date.now(),source:"performance",minutes:30});writeJson(TASKS_KEY,next);showFormMessage(root,`${area.key} çalışma görevi eklendi.`);window.dispatchEvent(new CustomEvent("nesevren-performance-updated"))}

function performancePrompt(){const records=performanceRecords();const summary=buildPerformanceSummary(records);const latest=records.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))||b.createdAt-a.createdAt).slice(0,6);const lines=latest.map(record=>`${record.name} (${record.examType}, ${record.date}): ${record.totalNet} net, ${record.durationMinutes} dk; ${record.subjects.map(item=>`${item.subject}${item.topic?`/${item.topic}`:""} ${item.net} net %${item.accuracyPercent}`).join(" | ")}`);return`Sen Neşevren'in kişiye özel eğitim koçu ve performans analistisin. Öğrencinin gerçek deneme kayıtlarını analiz et; genel tavsiye verme. Son net ${summary.latestTotalNet??"yok"}, önceki net ${summary.previousTotalNet??"yok"}, değişim ${summary.netChange??"yok"}, ortalama net ${summary.averageNet??"yok"}, en iyi net ${summary.bestNet??"yok"}, ortalama süre ${summary.averageDurationMinutes??"yok"} dakika. En zayıf alan ${summary.weakestArea?.key??"belirlenmedi"}; en güçlü alan ${summary.strongestArea?.key??"belirlenmedi"}. Denemeler: ${lines.join(" || ")||"henüz veri yok"}. 1) gelişimi kısa değerlendir, 2) en önemli 3 ders/konu önceliğini gerekçelendir, 3) süre yönetimi için somut hedef ver, 4) bir sonraki deneme için ölçülebilir net hedefi öner. Verinin desteklemediği kesin yargı kurma.`}

async function analyzePerformance(root){const records=performanceRecords();if(!records.length){showFormMessage(root,"Önce en az bir deneme sonucu ekle.",true);return}const button=root.querySelector("#performanceAi");const area=root.querySelector("#performanceAiResult");button.disabled=true;area.innerHTML='<div class="coachLoading"><b>✦</b><span>Deneme, net, süre ve ders gelişimini analiz ediyorum…</span></div>';try{const response=await fetch(`${API_URL}/api/v1/questions/analyze`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:performancePrompt(),inputType:"text",intent:"solve"})});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error?.message??"Performans analizi alınamadı.");const answer=data?.finalAnswer??data?.answer;if(!answer)throw new Error("Performans analizi boş döndü.");area.textContent="";const box=document.createElement("div");box.className="coachAiResult";const title=document.createElement("h4");title.textContent="📈 Kişisel performans analizin";box.appendChild(title);[answer.answer,answer.explanation].filter(Boolean).forEach(text=>{const p=document.createElement("p");p.textContent=text;box.appendChild(p)});if(Array.isArray(answer.steps)&&answer.steps.length){const ol=document.createElement("ol");answer.steps.forEach(step=>{const li=document.createElement("li");li.textContent=step;ol.appendChild(li)});box.appendChild(ol)}if(answer.hint){const p=document.createElement("p");p.textContent=`💡 ${answer.hint}`;box.appendChild(p)}area.appendChild(box)}catch(error){area.textContent="";const box=document.createElement("div");box.className="coachError";box.textContent=error instanceof Error?error.message:"Performans analizi hazırlanamadı.";area.appendChild(box)}finally{button.disabled=false}}

function wirePerformance(root){root.querySelector("#performanceExam")?.addEventListener("change",()=>{root.querySelectorAll(".performanceResultRow").forEach(row=>updateRowNet(root,row));renderPerformance(root)});root.querySelector("#performanceAddRow")?.addEventListener("click",()=>createResultRow(root));root.querySelector("#performanceSave")?.addEventListener("click",()=>savePerformance(root));root.querySelector("#performanceAi")?.addEventListener("click",()=>analyzePerformance(root));root.querySelector("#performanceTask")?.addEventListener("click",()=>addWeakAreaTask(root));createResultRow(root);renderPerformance(root)}

function ensurePerformanceSection(){const coach=document.getElementById("coachBackdrop");if(!coach||coach.querySelector("#performanceSection"))return;const roadmap=coach.querySelector(".coachRoadmapSection");const container=document.createElement("div");container.innerHTML=sectionMarkup();const section=container.firstElementChild;if(!section)return;if(roadmap)roadmap.insertAdjacentElement("afterend",section);else coach.querySelector(".coachBody")?.appendChild(section);wirePerformance(coach)}

const observer=new MutationObserver(ensurePerformanceSection);observer.observe(document.documentElement,{childList:true,subtree:true});ensurePerformanceSection();
window.addEventListener("storage",event=>{if(event.key===PERFORMANCE_KEY){const coach=document.getElementById("coachBackdrop");if(coach&&isVisible(coach))renderPerformance(coach)}});
