const STORAGE_KEY='nesevren-permissions-v1';
const state={bypassPhoto:false,bypassVoice:false};

function loadPrefs(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return{}}}
function savePref(kind,value){const next={...loadPrefs(),[kind]:value};try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next))}catch{}}
function findButton(text){return [...document.querySelectorAll('button')].find(b=>(b.textContent||'').includes(text))}
function closeModal(){document.querySelector('.nesevrenPermissionBackdrop')?.remove()}
function modal(kind,onChoice){closeModal();const isPhoto=kind==='photo';const wrap=document.createElement('div');wrap.className='nesevrenPermissionBackdrop';wrap.innerHTML=`<section class="nesevrenPermissionModal"><button class="permissionClose" aria-label="Kapat">×</button><div class="permissionIcon">${isPhoto?'📷':'🎙️'}</div><h2>${isPhoto?'Kamera ve fotoğraflar':'Mikrofon'} izni</h2><p>${isPhoto?'Neşevren, soru fotoğrafı çekebilmek veya yalnızca seçtiğin fotoğrafa erişebilmek için izin ister.':'Neşevren, sesli soru sorabilmen için mikrofon izni ister.'}</p><div class="permissionChoices"><button data-choice="full"><strong>Tam erişim</strong><span>${isPhoto?'Kamerayı kullan; galeri seçim ekranını da açabil.':'Bu cihazda mikrofon tercihini hatırla.'}</span></button><button data-choice="limited"><strong>Sınırlı erişim</strong><span>${isPhoto?'Yalnızca seçtiğin fotoğrafa eriş.':'Sadece bu kullanım için devam et; tercih kaydedilmez.'}</span></button><button data-choice="deny" class="deny"><strong>İzin verme</strong><span>Şimdilik erişim sağlama.</span></button></div><small>Not: Son sistem izin penceresi Android/iOS ve tarayıcı tarafından gösterilir; seçeneklerin adı cihazına göre değişebilir.</small></section>`;document.body.appendChild(wrap);wrap.querySelector('.permissionClose').onclick=closeModal;wrap.addEventListener('click',e=>{if(e.target===wrap)closeModal()});wrap.querySelectorAll('[data-choice]').forEach(btn=>btn.addEventListener('click',()=>{const choice=btn.dataset.choice;closeModal();onChoice(choice)}));}

function getExistingPhotoInput(){return document.querySelector('input[type="file"][accept*="image"]')}
function handFileToReact(file){const target=getExistingPhotoInput();if(!target||!file)return;try{const dt=new DataTransfer();dt.items.add(file);target.files=dt.files;target.dispatchEvent(new Event('change',{bubbles:true}))}catch{}}
function openGallery(){const picker=document.createElement('input');picker.type='file';picker.accept='image/jpeg,image/png,image/webp,image/heic,image/heif';picker.style.display='none';picker.onchange=()=>{const f=picker.files?.[0];if(f)handFileToReact(f);picker.remove()};document.body.appendChild(picker);picker.click()}
async function openCamera(){try{if(navigator.mediaDevices?.getUserMedia){const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});stream.getTracks().forEach(t=>t.stop())}}catch(err){alert('Kamera izni verilmedi veya kamera açılamadı.');return}const picker=document.createElement('input');picker.type='file';picker.accept='image/*';picker.setAttribute('capture','environment');picker.style.display='none';picker.onchange=()=>{const f=picker.files?.[0];if(f)handFileToReact(f);picker.remove()};document.body.appendChild(picker);picker.click()}
function photoActionSheet(){const wrap=document.createElement('div');wrap.className='nesevrenPermissionBackdrop';wrap.innerHTML=`<section class="nesevrenPermissionModal compact"><button class="permissionClose">×</button><div class="permissionIcon">📷</div><h2>Soru fotoğrafını nasıl eklemek istersin?</h2><div class="permissionChoices"><button data-photo="camera"><strong>Kamerayı Aç</strong><span>Şimdi yeni bir fotoğraf çek.</span></button><button data-photo="gallery"><strong>Galeriden Seç</strong><span>Yalnızca seçtiğin fotoğrafı kullan.</span></button></div></section>`;document.body.appendChild(wrap);wrap.querySelector('.permissionClose').onclick=closeModal;wrap.querySelector('[data-photo="camera"]').onclick=()=>{closeModal();openCamera()};wrap.querySelector('[data-photo="gallery"]').onclick=()=>{closeModal();openGallery()}}
async function handlePhotoPermission(choice){if(choice==='deny'){savePref('photo','deny');return}if(choice==='full'){savePref('photo','full');photoActionSheet();return}openGallery()}
async function handleVoicePermission(choice){if(choice==='deny'){savePref('microphone','deny');return}if(choice==='full')savePref('microphone','full');try{if(navigator.mediaDevices?.getUserMedia){const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop())}}catch{alert('Mikrofon izni verilmedi veya mikrofon açılamadı.');return}document.dispatchEvent(new CustomEvent('nesevren:voice-permitted',{detail:{mode:choice}}))}

function intercept(){document.addEventListener('click',e=>{const button=e.target.closest?.('button');if(!button)return;const text=button.textContent||'';
 if(text.includes('Fotoğrafla Sor')){if(state.bypassPhoto)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const pref=loadPrefs().photo;if(pref==='full'){photoActionSheet();return}modal('photo',c=>handlePhotoPermission(c));return}
 const isComposerVoice=button.classList.contains('composerVoiceButton');const isVoiceTrigger=isComposerVoice||text.includes('Sesli Sor')||text.includes('Dinliyorum')||text.includes('Devam Et');
 if(isVoiceTrigger){if(isComposerVoice&&button.classList.contains('voiceListening'))return;if(state.bypassVoice)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const pref=loadPrefs().microphone;if(pref==='full'){handleVoicePermission('full');return}modal('microphone',c=>handleVoicePermission(c));}
 },true)}

intercept();
