import type { AIAnswer, ProviderExecutor, QuestionAnalysis, SearchSource, StudentQuestion } from "./types.js";
import { buildIntentGuidance } from "./prompt-guidance.js";
import { parseVisualization, visualizationGuidance } from "./visualization.js";

const responseSchema={type:"OBJECT",properties:{answer:{type:"STRING"},explanation:{type:"STRING"},steps:{type:"ARRAY",items:{type:"STRING"}},hint:{type:"STRING"},detectedSubject:{type:"STRING"},detectedTopic:{type:"STRING"},visualization:{type:"STRING"}},required:["answer","explanation","steps","hint","detectedSubject","detectedTopic","visualization"]};
const factualTopics=new Set(["Genel","Fen Bilimleri","Fizik","Kimya","Biyoloji","Sosyal Bilgiler","Tarih","Coğrafya","Felsefe"]);
function shouldUseGoogleSearch(input:StudentQuestion,analysis:QuestionAnalysis){if(input.intent==="generate_test"||input.intent==="hint")return false;const q=input.question.toLocaleLowerCase("tr-TR");const explicit=/(güncel|bugün|şu an|son durum|son geliş|haber|internette|webde|google|araştır|kaynak|202[5-9]|kimdir|ne zaman|kaç yılında)/i.test(q);return explicit||factualTopics.has(analysis.topic)}
function buildPrompt(input:StudentQuestion,analysis:QuestionAnalysis,useGoogleSearch:boolean):string{const parts=["Sen Neşevren adlı yapay zekâ destekli çok dersli öğrenme platformunun eğitim motorusun.","ÖNEMLİ: Sorunun gerçek dersini içerikten kendin belirle. Kullanıcının arayüzde seçmiş olabileceği ders yalnızca bir ipucudur; içerikle çelişirse kesinlikle görmezden gel.","detectedSubject alanına yalnızca sorunun gerçek dersini yaz: Matematik, Fen Bilimleri, Fizik, Kimya, Biyoloji, Türkçe, Türk Dili ve Edebiyatı, İngilizce, Kürtçe, Sosyal Bilgiler, Tarih, Coğrafya veya Felsefe. detectedTopic alanına gerçek konuyu yaz.","Örneğin kullanıcı Edebiyat seçmiş olsa bile görselde matematik sorusu varsa detectedSubject mutlaka Matematik olmalıdır.","Türkçe, açık, pedagojik, öğrenci seviyesine uygun ve olgusal olarak doğru cevap ver. Dil dersi özellikle İngilizce veya Kürtçe ise gerektiğinde hedef dilde örnekler kullan.","Bilmediğin veya görselden okuyamadığın ayrıntıyı uydurma.",...(useGoogleSearch?["Google Search aracı etkin. Güncel veya olgusal bilgileri gerektiğinde web aramasıyla doğrula; arama sonucunda bulamadığın ayrıntıyı uydurma."]:[]),...(input.intent==="generate_test"?[]:[visualizationGuidance]),"Cevabı yalnızca istenen JSON şemasına uygun döndür.",`İstek türü: ${input.intent}`,`Ön analiz (yanlış olabilir): ${analysis.topic} / ${analysis.subtopic}`,`Sınav: ${analysis.exam}`,`Zorluk: ${analysis.difficulty}`,...buildIntentGuidance(input.intent)];if(input.inputType==="image")parts.push("Ekli kırpılmış görselde yalnızca seçili soruyu oku. Önce görselin gerçek dersini ve konusunu belirle; sonra çöz. Metni, sayıları, seçenekleri, sembolleri ve varsa şekil/tabloları dikkatlice yorumla. Geometri şekli önemliyse visualization alanında şekli yaklaşık yerleşimle yeniden kur; görselde olmayan veri ekleme. Görsel yeterince okunmuyorsa açıkça söyle.");if(input.question)parts.push(`Öğrencinin sorusu ve ek notu: ${input.question}`);return parts.join("\n")}
function parseDataUrl(dataUrl:string){const match=/^data:([^;,]+);base64,(.+)$/s.exec(dataUrl);if(!match)throw new Error("Gemini için görsel veri biçimi geçersiz.");return{mimeType:match[1],data:match[2]}}
type GroundingMetadata={groundingChunks?:Array<{web?:{uri?:string;title?:string}}>;webSearchQueries?:string[];searchEntryPoint?:{renderedContent?:string}};
function groundingDetails(metadata?:GroundingMetadata){const sources:SearchSource[]=[];const seen=new Set<string>();for(const chunk of metadata?.groundingChunks??[]){const url=chunk.web?.uri?.trim();if(!url||!/^https?:\/\//i.test(url)||seen.has(url))continue;seen.add(url);sources.push({title:chunk.web?.title?.trim()||"Web kaynağı",url});if(sources.length>=6)break}const queries=(metadata?.webSearchQueries??[]).filter((q):q is string=>typeof q==="string"&&Boolean(q.trim())).slice(0,6);const entry=metadata?.searchEntryPoint?.renderedContent?.trim();return{sources,queries,entry}}
function parseAnswer(raw:string,metadata?:GroundingMetadata):AIAnswer{let value:unknown;try{value=JSON.parse(raw)}catch{throw new Error("Gemini yapılandırılmış bir cevap döndürmedi.")}if(!value||typeof value!=="object")throw new Error("Gemini cevabı geçersiz.");const data=value as Record<string,unknown>;if(typeof data.answer!=="string"||typeof data.explanation!=="string"||!Array.isArray(data.steps)||!data.steps.every(i=>typeof i==="string")||typeof data.hint!=="string"||typeof data.detectedSubject!=="string"||typeof data.detectedTopic!=="string"||typeof data.visualization!=="string")throw new Error("Gemini cevabında zorunlu alanlar eksik.");const grounding=groundingDetails(metadata);return{answer:data.answer,explanation:data.explanation,steps:data.steps,hint:data.hint||undefined,detectedSubject:data.detectedSubject,detectedTopic:data.detectedTopic,visualization:parseVisualization(data.visualization),...(grounding.sources.length?{sources:grounding.sources}:{}),...(grounding.queries.length?{webSearchQueries:grounding.queries}:{}),...(grounding.entry?{googleSearchEntryPoint:grounding.entry}:{}),verified:false,verificationStatus:"pending",confidence:grounding.sources.length ? .88 : .8}}
type GeminiResponse={candidates?:Array<{content?:{parts?:Array<{text?:string}>};groundingMetadata?:GroundingMetadata}>;error?:{message?:string;status?:string;code?:number}};
async function callGemini(apiKey:string,model:string,parts:Array<Record<string,unknown>>,useGoogleSearch:boolean){const body:Record<string,unknown>={contents:[{role:"user",parts}],generationConfig:{responseMimeType:"application/json",responseSchema}};if(useGoogleSearch)body.tools=[{google_search:{}}];return fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":apiKey},body:JSON.stringify(body)})}
export const geminiExecutor:ProviderExecutor={providerId:"gemini",async execute(input,analysis){const apiKey=process.env.GEMINI_API_KEY?.trim();if(!apiKey)throw new Error("GEMINI_API_KEY tanımlı değil.");const model=process.env.GEMINI_MODEL?.trim()||"gemini-3.6-flash";const useGoogleSearch=shouldUseGoogleSearch(input,analysis);const prompt=buildPrompt(input,analysis,useGoogleSearch);const parts:Array<Record<string,unknown>>=[{text:prompt}];if(input.inputType==="image"&&input.imageDataUrl){const image=parseDataUrl(input.imageDataUrl);parts.push({inlineData:{mimeType:image.mimeType,data:image.data}})}let response=await callGemini(apiKey,model,parts,useGoogleSearch);let payload=await response.json() as GeminiResponse;if(!response.ok&&useGoogleSearch){response=await callGemini(apiKey,model,parts,false);payload=await response.json() as GeminiResponse}if(!response.ok)throw new Error(`Gemini çağrısı başarısız: ${response.status} ${payload.error?.message??response.statusText}`);const candidate=payload.candidates?.[0];const output=candidate?.content?.parts?.map(p=>p.text??"").join("").trim();if(!output)throw new Error("Gemini boş cevap döndürdü.");return parseAnswer(output,candidate?.groundingMetadata)}};

export { shouldUseGoogleSearch };
