import type { AIAnswer, ProviderExecutor, QuestionAnalysis, StudentQuestion } from "./types.js";
import { buildIntentGuidance } from "./prompt-guidance.js";
import { parseVisualization, visualizationGuidance } from "./visualization.js";

const responseSchema={type:"OBJECT",properties:{answer:{type:"STRING"},explanation:{type:"STRING"},steps:{type:"ARRAY",items:{type:"STRING"}},hint:{type:"STRING"},detectedSubject:{type:"STRING"},detectedTopic:{type:"STRING"},visualization:{type:"STRING"}},required:["answer","explanation","steps","hint","detectedSubject","detectedTopic","visualization"]};
function buildPrompt(input:StudentQuestion,analysis:QuestionAnalysis):string{const parts=["Sen Neşevren adlı yapay zekâ destekli çok dersli öğrenme platformunun eğitim motorusun.","ÖNEMLİ: Sorunun gerçek dersini içerikten kendin belirle. Kullanıcının arayüzde seçmiş olabileceği ders yalnızca bir ipucudur; içerikle çelişirse kesinlikle görmezden gel.","detectedSubject alanına yalnızca sorunun gerçek dersini yaz: Matematik, Fen Bilimleri, Fizik, Kimya, Biyoloji, Türkçe, Türk Dili ve Edebiyatı, İngilizce, Kürtçe, Sosyal Bilgiler, Tarih, Coğrafya veya Felsefe. detectedTopic alanına gerçek konuyu yaz.","Örneğin kullanıcı Edebiyat seçmiş olsa bile görselde matematik sorusu varsa detectedSubject mutlaka Matematik olmalıdır.","Türkçe, açık, pedagojik, öğrenci seviyesine uygun ve olgusal olarak doğru cevap ver. Dil dersi özellikle İngilizce veya Kürtçe ise gerektiğinde hedef dilde örnekler kullan.","Yanıtı gereksiz uzatma. Sonucu erken ver; açıklamayı özlü tut ve normal çözümlerde mümkünse 3-6 adımı geçme.","Bilmediğin veya görselden okuyamadığın ayrıntıyı uydurma.",...(input.intent==="generate_test"?[]:[visualizationGuidance]),"Cevabı yalnızca istenen JSON şemasına uygun döndür.",`İstek türü: ${input.intent}`,`Ön analiz (yanlış olabilir): ${analysis.topic} / ${analysis.subtopic}`,`Sınav: ${analysis.exam}`,`Zorluk: ${analysis.difficulty}`,...buildIntentGuidance(input.intent)];if(input.inputType==="image")parts.push("Ekli kırpılmış görselde yalnızca seçili soruyu oku. Önce görselin gerçek dersini ve konusunu belirle; sonra çöz. Metni, sayıları, seçenekleri, sembolleri ve varsa şekil/tabloları dikkatlice yorumla. Geometri şekli önemliyse visualization alanında şekli yaklaşık yerleşimle yeniden kur; görselde olmayan veri ekleme. Görsel yeterince okunmuyorsa açıkça söyle.");if(input.question)parts.push(`Öğrencinin sorusu ve ek notu: ${input.question}`);return parts.join("\n")}
function parseDataUrl(dataUrl:string){const match=/^data:([^;,]+);base64,(.+)$/s.exec(dataUrl);if(!match)throw new Error("Gemini için görsel veri biçimi geçersiz.");return{mimeType:match[1],data:match[2]}}
function parseAnswer(raw:string):AIAnswer{let value:unknown;try{value=JSON.parse(raw)}catch{throw new Error("Gemini yapılandırılmış bir cevap döndürmedi.")}if(!value||typeof value!=="object")throw new Error("Gemini cevabı geçersiz.");const data=value as Record<string,unknown>;if(typeof data.answer!=="string"||typeof data.explanation!=="string"||!Array.isArray(data.steps)||!data.steps.every(i=>typeof i==="string")||typeof data.hint!=="string"||typeof data.detectedSubject!=="string"||typeof data.detectedTopic!=="string"||typeof data.visualization!=="string")throw new Error("Gemini cevabında zorunlu alanlar eksik.");return{answer:data.answer,explanation:data.explanation,steps:data.steps,hint:data.hint||undefined,detectedSubject:data.detectedSubject,detectedTopic:data.detectedTopic,visualization:parseVisualization(data.visualization),verified:false,verificationStatus:"pending",confidence:.8}}
type GeminiResponse={candidates?:Array<{content?:{parts?:Array<{text?:string}>}}>;error?:{message?:string;status?:string;code?:number}};
async function callGemini(apiKey:string,model:string,parts:Array<Record<string,unknown>>,intent:StudentQuestion["intent"]){const body:Record<string,unknown>={contents:[{role:"user",parts}],generationConfig:{responseMimeType:"application/json",responseSchema,maxOutputTokens:intent==="generate_test"?8192:2048}};return fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":apiKey},body:JSON.stringify(body)})}
export const geminiExecutor:ProviderExecutor={providerId:"gemini",async execute(input,analysis){const apiKey=process.env.GEMINI_API_KEY?.trim();if(!apiKey)throw new Error("GEMINI_API_KEY tanımlı değil.");const model=process.env.GEMINI_MODEL?.trim()||"gemini-3.6-flash";const prompt=buildPrompt(input,analysis);const parts:Array<Record<string,unknown>>=[{text:prompt}];if(input.inputType==="image"&&input.imageDataUrl){const image=parseDataUrl(input.imageDataUrl);parts.push({inlineData:{mimeType:image.mimeType,data:image.data}})}const response=await callGemini(apiKey,model,parts,input.intent);const payload=await response.json() as GeminiResponse;if(!response.ok)throw new Error(`Gemini çağrısı başarısız: ${response.status} ${payload.error?.message??response.statusText}`);const output=payload.candidates?.[0]?.content?.parts?.map(p=>p.text??"").join("").trim();if(!output)throw new Error("Gemini boş cevap döndürdü.");return parseAnswer(output)}};
