import OpenAI from "openai";
import type { AIAnswer, ProviderExecutor, QuestionAnalysis, StudentQuestion } from "./types.js";
import { buildIntentGuidance } from "./prompt-guidance.js";
import { parseVisualization, visualizationGuidance } from "./visualization.js";

const answerSchema={type:"object",additionalProperties:false,properties:{answer:{type:"string"},explanation:{type:"string"},steps:{type:"array",items:{type:"string"}},hint:{type:"string"},visualization:{type:"string"}},required:["answer","explanation","steps","hint","visualization"]} as const;
function parseAnswer(raw:string):AIAnswer{let value:unknown;try{value=JSON.parse(raw)}catch{throw new Error("OpenAI yapılandırılmış bir cevap döndürmedi.")}if(!value||typeof value!=="object")throw new Error("OpenAI cevabı geçersiz.");const data=value as Record<string,unknown>;if(typeof data.answer!=="string"||typeof data.explanation!=="string"||!Array.isArray(data.steps)||!data.steps.every(i=>typeof i==="string")||typeof data.hint!=="string"||typeof data.visualization!=="string")throw new Error("OpenAI cevabında zorunlu alanlar eksik.");return{answer:data.answer,explanation:data.explanation,steps:data.steps,hint:data.hint||undefined,visualization:parseVisualization(data.visualization),verified:false,verificationStatus:"pending",confidence:.82}}
function buildPrompt(input:StudentQuestion,analysis:QuestionAnalysis):string{const parts=["Sen Neşevren adlı yapay zekâ destekli çok dersli öğrenme platformunun eğitim motorusun.","Matematikten fen bilimlerine, fizik, kimya, biyoloji, Türkçe, edebiyat, İngilizce, Kürtçe, sosyal bilgiler, tarih, coğrafya ve felsefeye kadar sorunun alanına uygun yöntem ve terminoloji kullan.","Türkçe, açık, pedagojik, öğrenci seviyesine uygun ve olgusal olarak doğru cevap ver. Dil sorularında gerektiğinde hedef dilde örnek kullan.","Bilmediğin ayrıntıyı uydurma. Öğrencinin düşünmesini destekle; gereksiz uzunluk ve cevabı ezberletme yaklaşımından kaçın.",visualizationGuidance,`İstek türü: ${input.intent}`,`Konu: ${analysis.topic} / ${analysis.subtopic}`,`Sınav: ${analysis.exam}`,`Zorluk: ${analysis.difficulty}`,...buildIntentGuidance(input.intent)];if(input.inputType==="image")parts.push("Ekli kırpılmış görselde yalnızca seçili soruyu oku; metin, sayı, seçenek, sembol, şekil ve tabloları dikkatle yorumla. Geometri şeklinin çözüm için önemli olduğu durumda visualization alanında yalnızca görselde gerçekten bulunan noktaları, kenarları ve açıları kullan. Okunmuyorsa açıkça söyle.");if(input.question)parts.push(`Öğrencinin sorusu ve ek notu: ${input.question}`);return parts.join("\n")}
export const openAIExecutor:ProviderExecutor={providerId:"openai",async execute(input,analysis){const apiKey=process.env.OPENAI_API_KEY?.trim();if(!apiKey)throw new Error("OPENAI_API_KEY tanımlı değil.");const client=new OpenAI({apiKey});const prompt=buildPrompt(input,analysis);const isImage=input.inputType==="image"&&Boolean(input.imageDataUrl);const model=isImage?(process.env.OPENAI_VISION_MODEL?.trim()||"gpt-5.6"):(process.env.OPENAI_MODEL?.trim()||"gpt-5.6-terra");const requestInput=isImage?[{role:"user" as const,content:[{type:"input_text" as const,text:prompt},{type:"input_image" as const,image_url:input.imageDataUrl!,detail:"high" as const}]}]:prompt;try{const response=await client.responses.create({model,input:requestInput,text:{format:{type:"json_schema",name:"nesevren_learning_answer",strict:true,schema:answerSchema}}});const output=response.output_text?.trim();if(!output)throw new Error("OpenAI boş cevap döndürdü.");return parseAnswer(output)}catch(error){const message=error instanceof Error?error.message:"Bilinmeyen OpenAI hatası";throw new Error(`${isImage?"Görsel":"Metin"} çağrısı başarısız: ${message}`)}}};
